version: '3.4'

name: dschinni

services:

  web:
    image: cvstoilov/dschinni-server
    container_name: server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      
  client:
    image: cvstoilov/dschinni-client
    container_name: client
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - web