# Generated by Django 4.2.7 on 2023-11-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='normal_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='promo_price',
            field=models.FloatField(null=True),
        ),
    ]
