# Generated by Django 4.2.7 on 2023-11-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_alter_product_normal_price_alter_product_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descrition',
            field=models.TextField(blank=True, max_length=355),
        ),
        migrations.AlterField(
            model_name='product',
            name='kit_scope',
            field=models.TextField(blank=True, max_length=355),
        ),
        migrations.AlterField(
            model_name='product',
            name='technical_details',
            field=models.TextField(blank=True, max_length=355),
        ),
    ]
