# Generated by Django 4.2.7 on 2023-11-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0008_productimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDelaySimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
